hello:
    path: /v1/hello
    controller: App\Controller\HelloController
    methods: GET 

get_customer_types:
    path: /v1/customers/types
    controller: App\Controller\CustomerTypesController::getCustomerTypes
    methods:    GET

get_identifier_types:
    path: /v1/customers/identifier-types
    controller: App\Controller\IdentifierTypesController::getIdentifierTypes
    methods:    GET

get_taxes_types_person:
    path: /v1/customers/taxes-types-person
    controller: App\Controller\TaxesTypesPersonController::getTypesPerson
    methods:    GET

#### ----- Countries ----------- ########
api_get_countries:
    path:       v1/customers/countries
    controller: App\Controller\CountriesController::getCountries
    methods:    GET

#### ----- Countries ----------- ########


#### ----- States ----------- ########
api_get_states_by_country:
    path:       v1/customers/countries/{countryId}/states
    controller: App\Controller\StatesController::getStatesByCountryId
    methods:    GET

#### ----- States ----------- ########

#### ----- Cities ----------- ########
api_get_cities_by_state:
    path:       v1/customers/states/{stateId}/cities
    controller: App\Controller\CitiesController::getCitiesByStateId
    methods:    GET

#### ----- Cities ----------- ########

create_customers:
    path: /v1/customers
    controller: App\Controller\CustomersController::create
    methods:    POST

update_customers:
    path: /v1/customers/{customerTypeId}/{identifierTypeId}/{customerId}
    controller: App\Controller\CustomersController::update
    methods:    PUT

get_emails:
    path: /v1/customers/emails
    controller: App\Controller\GetCustomersEmail::getEmails
    methods: POST

get_customer_file:
    path: v1/customers/files/{customerFileId}
    controller: App\Controller\GetCustomerFileByCustomerFileIdController::getFileByCustomerFileId
    methods:    GET








create_customers_by_CVS:
    path: /v1/customers-csv
    controller: App\Controller\CreateCustomersByCSVController::createBasicResidentialCustomersByCSV
    methods:    POST     

create_customers_by_CVS_MARZO:
    path: /v1/customers-csv/marzo
    controller: App\Controller\CreateCustomersByCSVController::createCVSMarch
    methods:    POST  


create_customers_by_CVS_Appointments:
    path: /v1/customers-csv/appointments
    controller: App\Controller\CreateCustomersByCSVController::createCsvAppointments
    methods:    POST        



retrieve_customers:
    path: /v1/retrieveCustomers
    controller: App\Controller\retrieveCustomersController::retrieveListCustomers
    methods:    GET 

retrieve_customers_info:
    path: /v1/customers/retrieve-customers-info
    controller: App\Controller\RetrieveCustomersInfoController::retrieveCustomersInfo
    methods: POST 

retrieve_basic_customers_between_microservices:
    path: /v1/customers/retrieve-basic-customers-info
    controller: App\Controller\RetrieveBasicCustomersBetweenMicroservicesController::retrieveBasicCustomersBetweenMicroservices
    methods: POST     

retrieve_basic_customers_by_expression:
    path: /v1/customers/retrieve-expression-customers
    controller: App\Controller\RetrieveBasicCustomersByExpressionController::retrieveBasicCustomersBetweenMicroservices
    methods: GET

retrieve_customers_by_expression:
    path: /v1/retrievecustomer/expression
    controller: App\Controller\ExrpressionRetrieveCustomersController::retrieveCustomersByExpression
    methods: GET


get_customer_by_ids:
    path: v1/customers/{customerTypeId}/{identifierTypeId}/{customerId}
    controller: App\Controller\GetCustomerByIdsController::getCustomerByIds
    methods:    GET

get-basic-customer:
    path: v1/customers/basic-customer/{customerTypeId}/{identificationTypeId}/{identificationvalue}
    controller: App\Controller\GetCustomerBasicInfoByIdsController::getCustomerByIds
    methods:    GET        

#get_customer:
    #path: v1/customers/{customerTypeId}/{identificationTypeId}/{identificationvalue}
    # the controller value has the format 'controller_class::method_name' 
    #controller: App\Controller\GetCustomerByIdsController::getCustomerByIds
    #methods:    GET

    