hello:
    path: /v1/hello
    controller: App\Controller\HelloController
    methods: GET 

create_customers:
    path: /v1/customers
    controller: App\Controller\CustomersController::create
    methods:    POST   

create_customers_by_CVS:
    path: /v1/customers-csv
    controller: App\Controller\CreateCustomersByCSVController::createBasicResidentialCustomersByCSV
    methods:    POST     

update_customers:
    path: /v1/customers
    # the controller value has the format 'controller_class::method_name' 
    controller: App\Controller\CustomersController::update
    methods:    PUT  

retrieve_customers:
    path: /v1/retrieveCustomers
    controller: App\Controller\retrieveCustomersController::retrieveListCustomers
    methods:    GET 

retrieve_customers_info:
    path: /v1/customers/retrieve-customers-info
    controller: App\Controller\RetrieveCustomersInfoController::retrieveCustomersInfo
    methods: POST 

retrieve_customers_by_expression:
    path: /v1/retrievecustomer/expression
    controller: App\Controller\ExrpressionRetrieveCustomersController::retrieveCustomersByExpression
    methods: GET     

get_customer:
    path: v1/customer/{customerTypeId}/{identificationTypeId}/{identificationvalue}
    # the controller value has the format 'controller_class::method_name' 
    controller: App\Controller\GetCustomerByIdsController::getCustomerByIds
    methods:    GET    

    